# Project information
site_name: Awesome TM1 Planning Analytics
site_description: "MkDocs Material Boilerplate (Starter Kit) - Deploy documentation to hosting platforms (Netlify, GitHub Pages, GitLab Pages, and AWS Amplify Console) with Docker, pipenv, and GitHub Actions."
site_author: "Kevin Lou"
site_url: "https://mkdocs.peaceiris.com/"

# Copyright
copyright: Copyright &copy; 2022 - 2024 Kevin Lou

# Repository
repo_name: kevin7lou/awesome-tm1-planning-analytics
repo_url: https://github.com/kevin7lou/awesome-tm1-planning-analytics
# edit_uri: "https://github.com/peaceiris/mkdocs-material-boilerplate/edit/main/docs_sample"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "blue"
    accent: "blue"
  features:
    - tabs
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/peaceiris"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/piris314en"

# Page tree
nav:
  - Home: index.md
  - Performanece: performance.md
  # - "Home": "index.md"
  # - "Material for MkDocs": "material-for-mkdocs.md"
  # - "Getting started":
  #     - "Download boilerplate": "getting-started/download-boilerplate.md"
  #     - "pipenv": "getting-started/pipenv.md"
  #     - "invoke": "getting-started/invoke.md"
  #     - "Docker": "getting-started/docker.md"
  #     - "pip": "getting-started/pip.md"
  # - "Hosting and Deployment":
  #     - "Combinations": "hosting-and-deployment/combinations.md"
  #     - "Netlify": "hosting-and-deployment/netlify.md"
  #     - "GitHub Pages": "hosting-and-deployment/github-pages.md"
  #     - "GitLab Pages": "hosting-and-deployment/gitlab-pages.md"
  #     - "AWS Amplify Console": "hosting-and-deployment/aws-amplify-console.md"
  # - "Extensions":
  #     - "MathJax": "extensions/mathjax.md"
  #     - "Code Hilite": "extensions/code-hilite.md"
  #     - "Footnote": "extensions/footnote.md"
  # - "License": "license.md"
